from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

from agent.tools.base import BaseTool


class ReportWriterInput(BaseModel):
    title: str = Field(description="Report title")
    sections: list[str] = Field(description="Ordered section headings")
    content: dict[str, str] = Field(
        description="Mapping of section heading to section content"
    )
    save_to_file: bool = Field(
        default=True, description="Save report to data/reports/ (recommended: true)"
    )


class ReportWriterTool(BaseTool):
    name = "report_writer"
    description = (
        "Generate a structured Markdown report from provided sections and content. "
        "Saves to data/reports/ by default. Use this whenever the user asks for a "
        "report, document, summary, or written output."
    )

    def get_schema(self) -> type[BaseModel]:
        return ReportWriterInput

    async def _execute(
        self,
        title: str,
        sections: list[str],
        content: dict[str, str],
        save_to_file: bool = False,
    ) -> str:
        return await asyncio.to_thread(
            self._build_report, title, sections, content, save_to_file
        )

    def _build_report(
        self,
        title: str,
        sections: list[str],
        content: dict[str, str],
        save_to_file: bool,
    ) -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# {title}",
            "",
            f"*Generated: {now}*",
            "",
            "## Table of Contents",
            "",
        ]

        for i, sec in enumerate(sections, 1):
            anchor = sec.lower().replace(" ", "-")
            lines.append(f"{i}. [{sec}](#{anchor})")

        lines.append("")
        lines.append("---")
        lines.append("")

        for sec in sections:
            lines.append(f"## {sec}")
            lines.append("")
            lines.append(content.get(sec, "*No content provided.*"))
            lines.append("")

        lines.append("---")
        lines.append(f"*Report generated by RAG-Agent*")

        report = "\n".join(lines)

        if save_to_file:
            reports_dir = Path("data/reports")
            reports_dir.mkdir(parents=True, exist_ok=True)
            slug = title.lower().replace(" ", "_")[:50]
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            filepath = reports_dir / f"{slug}_{ts}.md"
            filepath.write_text(report, encoding="utf-8")
            return f"Report saved to {filepath}\n\n{report}"

        return report
